// View Page
const DASHBOARD = {
    REQUEST: 'DASHBOARD_REQUEST',
    SUCCESS: 'DASHBOARD_SUCCESS',
    FAILURE: 'DASHBOARD_FAILURE',
    GRAPH_SUCCESS: 'DASHBOARD_GRAPH_SUCCESS',
    GRAPH_FAILURE: 'DASHBOARD_GRAPH_FAILURE',
    NOTIFICATION: 'DASHBOARD_NOTIFICATION',
    ERRORSYSTEM: 'DASHBOARD_ERRORSYSTEM',
    ERRORSYSTEM_RESET: 'DASHBOARD_ERRORSYSTEM_RESET',
    LATEST_DATA_SUCCESS: 'LATEST_DATA_SUCCESS',

}
const COURSE = {
  REQUEST: 'COURSE_REQUEST',
  SUCCESS: 'COURSE_SUCCESS',
  FAILURE: 'COURSE_FAILURE',
  GRAPH_SUCCESS: 'COURSE_GRAPH_SUCCESS',
  GRAPH_FAILURE: 'COURSE_GRAPH_FAILURE',
  NOTIFICATION: 'COURSE_NOTIFICATION',
  ERRORSYSTEM: 'COURSE_ERRORSYSTEM',
  ERRORSYSTEM_RESET: 'COURSE_ERRORSYSTEM_RESET',
  LATEST_DATA_SUCCESS: 'LATEST_DATA_SUCCESS',

  COURSE_REGISTRATION_TABLE: 'COURSE_REGISTRATION_TABLE',
  COURSE_REGISTRATION_LIST: 'COURSE_REGISTRATION_LIST',
  CHECK_TABLE_LIST: 'CHECK_TABLE_LIST',
  CHECK_COURSE_LIST: 'CHECK_COURSE_LIST',
  GET_COURSE_LIST: 'GET_COURSE_LIST',
  GET_TIMETABLE_LIST: 'GET_TIMETABLE_LIST',
  GET_SELECTED_TIMETABLE_LIST: 'GET_SELECTED_TIMETABLE_LIST',
  CHECK_ELIGIBLE: "CHECK_ELIGIBLE",
  GET_REGISTER_TIME_TABLE: 'GET_REGISTER_TIME_TABLE',

  GET_CURRICULUM_LIST: 'GET_CURRICULUM_LIST',
  SHOW_TIME_TABLE: 'SHOW_TIME_TABLE'
}

const CURRICULUM = {
  REQUEST: 'CURRICULUM_REQUEST',
  SUCCESS: 'CURRICULUM_SUCCESS',
  FAILURE: 'CURRICULUM_FAILURE',
  GRAPH_SUCCESS: 'CURRICULUM_GRAPH_SUCCESS',
  GRAPH_FAILURE: 'CURRICULUM_GRAPH_FAILURE',
  NOTIFICATION: 'CURRICULUM_NOTIFICATION',
  ERRORSYSTEM: 'CURRICULUM_ERRORSYSTEM',
  ERRORSYSTEM_RESET: 'CURRICULUM_ERRORSYSTEM_RESET',
  LIST_CURRICULUM: 'LIST_CURRICULUM',
}

const STUDENT = {
  REQUEST: 'STUDENT_REQUEST',
  SUCCESS: 'STUDENT_SUCCESS',
  FAILURE: 'STUDENT_FAILURE',
  GRAPH_SUCCESS: 'STUDENT_GRAPH_SUCCESS',
  GRAPH_FAILURE: 'STUDENT_GRAPH_FAILURE',
  NOTIFICATION: 'STUDENT_NOTIFICATION',
  ERRORSYSTEM: 'STUDENT_ERRORSYSTEM',
  ERRORSYSTEM_RESET: 'STUDENT_ERRORSYSTEM_RESET',
  LIST_STUDENT: 'LIST_STUDENT',

  STUDENT_COUNT_CHANGE: 'STUDENT_COUNT_CHANGE',
  STUDENT_PAGE_CHANGE: 'STUDENT_PAGE_CHANGE',

  STUDENT_SEARCH: 'STUDENT_SEARCH'
}
const LECTURER = {
  REQUEST: 'LECTURER_REQUEST',
  SUCCESS: 'LECTURER_SUCCESS',
  FAILURE: 'LECTURER_FAILURE',
  GRAPH_SUCCESS: 'LECTURER_GRAPH_SUCCESS',
  GRAPH_FAILURE: 'LECTURER_GRAPH_FAILURE',
  NOTIFICATION: 'LECTURER_NOTIFICATION',
  ERRORSYSTEM: 'LECTURER_ERRORSYSTEM',
  ERRORSYSTEM_RESET: 'LECTURER_ERRORSYSTEM_RESET',
  LIST_LECTURER: 'LIST_LECTURER',
}
const SECTION = {
  REQUEST: 'SECTION_REQUEST',
  SUCCESS: 'SECTION_SUCCESS',
  FAILURE: 'SECTION_FAILURE',
  GRAPH_SUCCESS: 'SECTION_GRAPH_SUCCESS',
  GRAPH_FAILURE: 'SECTION_GRAPH_FAILURE',
  NOTIFICATION: 'SECTION_NOTIFICATION',
  ERRORSYSTEM: 'SECTION_ERRORSYSTEM',
  ERRORSYSTEM_RESET: 'SECTION_ERRORSYSTEM_RESET',
  LIST_SECTION: 'LIST_SECTION',
  SECTION_LIST_BY_ID: 'SECTION_LIST_BY_ID'
}

const REGISTRATION_SCHEDULE = {

  REQUEST: 'REGISTRATION_SCHEDULE_REQUEST',
  SUCCESS: 'REGISTRATION_SCHEDULE_SUCCESS',
  FAILURE: 'REGISTRATION_SCHEDULE_FAILURE',
  GRAPH_SUCCESS: 'REGISTRATION_SCHEDULE_GRAPH_SUCCESS',
  GRAPH_FAILURE: 'REGISTRATION_SCHEDULE_GRAPH_FAILURE',
  NOTIFICATION: 'REGISTRATION_SCHEDULE_NOTIFICATION',
  ERRORSYSTEM: 'REGISTRATION_SCHEDULE_ERRORSYSTEM',
  ERRORSYSTEM_RESET: 'REGISTRATION_SCHEDULE_ERRORSYSTEM_RESET',
  LIST_REGISTRATION_SCHEDULE: 'LIST_REGISTRATION_SCHEDULE',
}

const USER = {
    // SEARCH: 'USERS_SEARCH',
    LIST_REQUEST: 'USERS_LIST_REQUEST',
    LIST_SUCCESS: 'USERS_LIST_SUCCESS',
    LIST_FAILURE: 'USERS_LIST_FAILURE',

    REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',

    UPDATE_REQUEST: 'USERS_UPDATE_REQUEST',
    UPDATE_SUCCESS: 'USERS_UPDATE_SUCCESS',
    UPDATE_FAILURE: 'USERS_UPDATE_FAILURE',

    FIND_REQUEST: 'USERS_FIND_REQUEST',
    FIND_SUCCESS: 'USERS_FIND_SUCCESS',
    FIND_FAILURE: 'USERS_FIND_FAILURE',

    DELETE_REQUEST: 'USERS_DELETE_REQUEST',
    DELETE_SUCCESS: 'USERS_DELETE_SUCCESS',
    DELETE_FAILURE: 'USERS_DELETE_FAILURE',

    CHANGE_PASSWORD_REQUEST: 'CHANGE_PASSWORD_REQUEST',
    CHANGE_PASSWORD_SUCCESS: 'CHANGE_PASSWORD_SUCCESS',
    CHANGE_PASSWORD_FAILURE: 'CHANGE_PASSWORD_FAILURE',

    RESET_PASSWORD_REQUEST: 'RESET_PASSWORD_REQUEST',
    RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS',
    RESET_PASSWORD_FAILURE: 'RESET_PASSWORD_FAILURE',

    USERS_COUNT_CHANGE: 'USERS_COUNT_CHANGE',
    USERS_PAGE_CHANGE: 'USERS_PAGE_CHANGE',

    USERS_SEARCH: 'USERS_SEARCH'
}
const DEVICEDATA = {
    DATA: 'DATA',
    LATEST_READING: 'DEVICEDATA_LATEST_READING',
    LAST_READING: 'DEVICEDATA_LAST_READING',
    AVERAGE_READING: 'DEVICEDATA_AVERAGE_READING',
    AVERAGE_ERROR: 'DEVICEDATA_AVERAGE_ERROR',
    TOTAL_ERROR: 'DEVICEDATA_TOTAL_ERROR'
}
const HISTORY = {
    FIND_SUCCESS: 'HISTORY_FIND_SUCCESS',
    FIND_FAILURE: 'HISTORY_FIND_FAILURE',
    // UPDATE_SUCCESS: 'HISTORY_UPDATE_SUCCESS',
    // UPDATE_FAILURE: 'HISTORY_UPDATE_FAILURE',
    LOGS_COUNT_CHANGE: 'LOGS_COUNT_CHANGE',
    LOGS_PAGE_CHANGE: 'LOGS_PAGE_CHANGE',
}
const DEVICE = {
    REGISTER_REQUEST: 'DEVICE_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'DEVICE_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'DEVICE_REGISTER_FAILURE',

    LIST_REQUEST: 'DEVICE_LIST_REQUEST',
    LIST_SUCCESS: 'DEVICE_LIST_SUCCESS',
    LIST_FAILURE: 'DEVICE_LIST_FAILURE',

    UPDATE_REQUEST: 'DEVICE_UPDATE_REQUEST',
    UPDATE_SUCCESS: 'DEVICE_UPDATE_SUCCESS',
    UPDATE_FAILURE: 'DEVICE_UPDATE_FAILURE',

    FIND_REQUEST: 'DEVICE_FIND_REQUEST',
    FIND_SUCCESS: 'DEVICE_FIND_SUCCESS',
    FIND_FAILURE: 'DEVICE_FIND_FAILURE',

    DELETE_REQUEST: 'DEVICE_DELETE_REQUEST',
    DELETE_SUCCESS: 'DEVICE_DELETE_SUCCESS',
    DELETE_FAILURE: 'DEVICE_DELETE_FAILURE',

    INACTIVE: 'inactive',
    ACTIVE:'active',
    DISPOSE: 'dispose',

    SEARCH: 'DEVICES_SEARCH',
}

// Others
const ROLE = {
    ADMIN: 'admin',
    MANAGER: 'manager',
    STUDENT: 'Student',
    LECTURER: 'Lecturer'
}

const PATH = {
    LOGIN: '/login'
}

export const CONSTANTS = {
    CLEAR: 'CLEAR',
    TIME_IDLE: 30, // value in minute

    DASHBOARD,
    CURRICULUM,
    STUDENT,
    LECTURER,
    SECTION,
    COURSE,
    USER,
    DEVICEDATA,
    DEVICE,
    HISTORY,
    REGISTRATION_SCHEDULE,

    ROLE,
    PATH,
}
